### ISSUE TITLE
cards do not align correctly in Safari

### ISSUE THREAD

**Issue by johnrlive** [sharu725/cards#11]
The cards do not align the same as Chrome. Do the cards alignment look the same on Chrome & Safari?

**Comment by sharu725** [comment]
For some reason, flex-box is not working on Safari. A quick fix would be adding this CSS to _custom.scss found inside sass folder.

```
.card {
     display: -webkit-inline-box;
    height: 500px;
}     
```

Let me see what can be done to solve the problem permanently.

**Comment by thinkingsand** [comment]
Hi. Did you ever find a permanent fix for this? We're still having issues, even after intergrating that CSS code.

**Comment by sharu725** [comment]
@Mcharlsto can you post a screenshot of what issue you are facing?

**Comment by thinkingsand** [comment]
@sharu725 I've attached two - the first is the site rendering correctly in Firefox, the second is shows the issue in Safari.

![firefoxScreenshot](https://user-images.githubusercontent.com/2265483/86511439-2d1f1080-bdf1-11ea-9ffc-14ef29328f5d.png)
![safariScreenshot](https://user-images.githubusercontent.com/2265483/86511441-30b29780-bdf1-11ea-982e-7c60e6730432.png)

If you need to investigate at all, the code is available at github.com/leedsraspjam/www and the site is at leedsraspjam.co.uk. Thanks for helping.

**Comment by sharu725** [comment]
@Mcharlsto please check it now. Updated the layout.

**Comment by thinkingsand** [comment]
@sharu725 All works fine. Thanks for your help.
