### ISSUE TITLE
 jekyll   Dependency Error

### ISSUE THREAD

**Issue by jiehu567** [sharu725/cards#12]
After I run 'jekyll serve', I get issue on my mac:

Configuration file: /Users/hujie/Documents/MyWebsite/cards-master/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-seo-tag or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-seo-tag' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

Jekyll version: 3.3.1

**Comment by sharu725** [comment]
Run `gem install jekyll-seo-tag`. Prefix sudo if necessary.
[https://github.com/jekyll/jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)

**Comment by jiehu567** [comment]
Tnx for reply, but still got same msg:

hujiedeMacBook-Pro:cards-master hujie$ sudo gem install jekyll-seo-tag
Password:
Fetching: jekyll-3.3.1.gem (100%)
/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:6: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Successfully installed jekyll-3.3.1
Fetching: jekyll-seo-tag-2.1.0.gem (100%)
Successfully installed jekyll-seo-tag-2.1.0
2 gems installed
hujiedeMacBook-Pro:cards-master hujie$ jekyll serve
Configuration file: /Users/hujie/Documents/MyWebsite/cards-master/_config.yml
Configuration file: /Users/hujie/Documents/MyWebsite/cards-master/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.3.1 | Error:  jekyll-paginate

**Comment by sharu725** [comment]
Well, that solved one problem. Now you should install jekyll-paginate gem the same way. This is because inside _config.yml file there is a field called gems.

`gems: [jekyll-paginate, jekyll-seo-tag]`

If you remove them then the theme will be served but you might lose some functionalities.

It is good to install missing gems. 

`gem install jekyll-paginate`

should solve your issue.

**Comment by jiehu567** [comment]
Tnx so much, it solved the problem.

**Comment by sharu725** [comment]
Welcome
