### ISSUE TITLE
 Problem for to get started localhost

### ISSUE THREAD

**Issue by MichelCordeiro** [sharu725/cards#9]
localhost does not recognize the 

{{site.baseurl}}

**Comment by sharu725** [comment]
@MichelCordeiro thanks for reporting the issue. I checked it and it works for me in local env.
When you serve locally, the URL you should be looking for is `http://127.0.0.1:4000/cards/` . Please let me know exactly where this problem is happening.

**Comment by MichelCordeiro** [comment]
Thanks @sharu725 !! 

I forgot jekyll server command 
(-_-)
